name: Kernel Build

on:
  workflow_dispatch:

jobs:
  kb:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache clang and build-tools
      uses: actions/cache@v4
      with:
        path: |
          ../clang-r450784d
          ../build-tools
        key: ${{ runner.os }}-clang450784d

    - name: Install tools
      run: |
        sudo apt-get update -y &>/dev/null || sudo apt-get update -y &>/dev/null || true
        sudo apt-get upgrade -y &>/dev/null || sudo apt-get upgrade -y &>/dev/null || true
        sudo apt-get install brotli zip zstd tar lz4 cpio xz-utils pahole libelf-dev python2 -y || sudo apt-get install python2 pahole libelf-dev brotli zip zstd tar lz4 cpio xz-utils -y
    - name: Build
      run: |
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -
        bash build.sh
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: |
          kernel_build/ExynosUnboundA14.zip
          kernel_build/ExynosUnboundA14.tar
